config/routes.rb
ParasquidCs2001::Application.routes.draw do
  root to: "welcome#index"

  get "querying" => 'querying#index'

  get "uploads" => 'uploads#index'
  post "upload_prediction_data" => "uploads#upload_prediction_data"
  
  namespace :uploads do
    post "challenge_platforms"
    post "challenge_technologies"
    post "challlenges"
    post "challenge_participants"
    get "generate_prediction_data"
  end

  match '/query' => Prediction, anchor: false
end

app/models/active_model/model.rb
module ActiveModel
  module Model
    def self.included(base)
      base.class_eval do
        extend  ActiveModel::Naming
        extend  ActiveModel::Translation
        include ActiveModel::Validations
        include ActiveModel::Conversion
      end
    end

    def initialize(params={})
      params.each do |attr, value|
        self.public_send("#{attr}=", value)
      end if params
    end

    def persisted?
      false
    end
  end
end

app/models/prediction_data.rb
require "csv"

class PredictionData
	include Mongoid::Document

	field :platforms, type: Array, default: []
	field :technologies, type: Array, default: []
	field :submitters, type: Array, default: []
	field :total_prize, type: Integer, default: 0
	field :top_prize, type: Integer, default: 0
	field :challenge_length, type: Integer, default: 0
	field :passing_submissions, type: Float, default: 0.0

	def self.session
		@session ||= Mongoid::Sessions.default
	end

	def self.import_challenge_platforms(data)
		column_name = :challenge_platforms
		session[column_name].drop
		session[column_name].insert(data)
	end

	def self.import_challenge_technologies(data)
		column_name = :challenge_technologies
		session[column_name].drop
		session[column_name].insert(data)
	end

	def self.import_challenges(data)
		column_name = :challenges
		session[column_name].drop
		session[column_name].insert(data)
	end

	def self.import_challenge_participants(data)
		column_name = :challenge_participants
		session[column_name].drop
		session[column_name].insert(data)
	end

	def self.generate
		# generate the prediction data lines
		# platforms.join(' '), technologies.join(' '), submitters.join(' '), total_prize, top_prize, challenge_length, passing_submissions
		lines = {}

		# reduce the challenge platforms into lines and arrays by creating a hash
		session[:challenge_platforms].find.each do |row|
			cid = row["Challenge__r.Challenge_Id__c"]
			lines[cid] ||= {}
			lines[cid][:platforms] ||= []
			lines[cid][:platforms].push(row["Platform__r.Name"])
		end

		session[:challenge_technologies].find.each do |row|
			cid = row["Challenge__r.Challenge_Id__c"]
			lines[cid] ||= {}
			lines[cid][:technologies] ||= []
			lines[cid][:technologies].push(row["Technology__r.Name"])
		end

		# include the challenge info
		session[:challenges].find.each do |row|
			cid = row["Challenge_Id__c"]
			lines[cid] ||= {}
			lines[cid][:challenge_length] = row["Length_of_Contest__c"].to_i
			lines[cid][:top_prize] = row["Top_Prize__c"].to_s.gsub('$','').gsub(',','').to_i
			lines[cid][:total_prize] = row["Total_Prize_Money__c"].to_i
		end

		# include the submitters
		session[:challenge_participants].find.each do |row|
			cid = row["Challenge__r.Challenge_Id__c"]
			score = row["Score__c"].to_f
			lines[cid] ||= {}
			lines[cid][:submitters] ||= []
			lines[cid][:submitters].push(row["Member__r.Name"]) if score > 0
			lines[cid][:passing_submissions] ||= 0
			lines[cid][:passing_submissions] += 1 if score > 75
		end

		# create the database
		lines.each do |cid, data|
			PredictionData.create data
		end

		# clear in-memory database
	end

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      self.all.each do |elem|
				csv << [elem.passing_submissions,
					"#{elem.platforms.sort.join(' ')}",
					"#{elem.technologies.sort.join(' ')}",
					"#{elem.submitters.sort.join(' ')}",
					elem.total_prize,
					elem.top_prize,
					elem.challenge_length
				]
      end
    end
  end

	private

	def self.sanitize(data, column_names)
    data.each do |row|
			row.delete_if {|key, value| !column_names.include? key.to_sym}
		end
	end

	def self.insert_into_database(data, column_name)
		data = sanitize(data, DB[column_name].columns)
		data.each do |row|
			begin
				DB[column_name.to_sym].insert row
			rescue Exception => e
				Rails.logger.error e.inspect # log exceptions but continue anyway
			end
		end
	end
end

app/models/upload.rb
class Upload
	include ActiveModel::Model

	attr_accessor :data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/querying_controller.rb
class QueryingController < ApplicationController
  def index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	def index
		@upload = Upload.new
		@challenge_participants = PredictionData.session[:challenge_participants].find
		@challenges = PredictionData.session[:challenges].find
    @challenge_platforms = PredictionData.session[:challenge_platforms].find
		@challenge_technologies = PredictionData.session[:challenge_technologies].find
	end

  def challenge_platforms
    data = HashableCSV.new params[:upload][:data].tempfile
    PredictionData.import_challenge_platforms(data.to_hash)
    redirect_to uploads_path
  end

  def challenge_technologies
		data = HashableCSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenge_technologies(data.to_hash)
  	redirect_to uploads_path
  end

  def challlenges
		data = HashableCSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenges(data.to_hash)
  	redirect_to uploads_path
  end

  def challenge_participants
		data = HashableCSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenge_participants(data.to_hash)
  	redirect_to uploads_path, notice: 'Upload completed'
  end

  def generate_prediction_data
    # drop it like it's hot
    PredictionData.delete_all
    PredictionData.generate
  	send_data PredictionData.to_csv, filename: 'prediction_data.csv'
  end

  def upload_prediction_data
    PredictionData.delete_all
    PredictionData.generate

    gs = GoogleStorage.new
    gs.upload_prediction_data(PredictionData.to_csv)

    redirect_to root_path, notice: 'Successfully uploaded Prediction Data'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/querying_helper.rb
module QueryingHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParasquidCs2001</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="row">
<div class="span12">
	<%= yield %>
</div>
</div>
</div>
</body>
</html>

app/views/querying/index.html.erb
<h1>Querying#index</h1>
<p>Find me in app/views/querying/index.html.erb</p>

app/views/uploads/index.html.erb
<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challenge_participants_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-participants-export.csv' %>
	<div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-danger">Create Upload</button> <%= @challenge_participants.count %> records
    </div>
  </div>
	<% end %>
</div>

<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challlenges_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-export.csv' %>
		<div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-warning">Create Upload</button> <%= @challenges.count %> records
	    </div>
	  </div>
	<% end %>
</div>

<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challenge_platforms_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-platforms-export.csv' %>
		<div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-success">Create Upload</button> <%= @challenge_platforms.count %> records
	    </div>
	  </div>
	<% end %>
</div>

<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challenge_technologies_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-technologies-export.csv' %>
		<div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-success">Create Upload</button> <%= @challenge_technologies.count %> records
	    </div>
	  </div>
	<% end %>
</div>

<%= link_to "Back", root_path, :class => 'btn btn-primary' %>

app/views/welcome/index.html.erb
<h1>Welcome to the Cloudspokes Google Prediction API Challenge</h1>
<h4>You need to perform these steps</h4>
<ol>
	<li><%= link_to "Upload", uploads_path %> the data exports</li>
	<li><%= link_to "Download", uploads_generate_prediction_data_path %> the prediction data</li>
	<li><%= link_to "Import", "https://storage.cloud.google.com/", target: '_blank' %> the prediction data into Google Cloud Storage</li>
	<li><%= link_to "Query", query_path %> the prediction api</li>
</ol>

<hr>
<h4>Or You can use the following script to automate the above process.</h4>

<ol>
  <li>Download <a href="/feed_data">feed_data script</a> </li>
  <li>
    Make it executable
    <pre> chmod +x feed_data </pre>
  </li>
  <li>
    Change script's configuration
    <pre>  DIR="."                 # directory that csv files are
  SERVER="localhost:5000" # the host name of the server </pre>
  </li>
  <li> 
    Execute the script. <br/>
    It will upload csv files and generates prediction_data.csv at the Google Cloud Storage
  </li>
</ol>

<p>Note : Requried csv files are </p>
<pre>  challenges-export.csv 
  challenge-participatns-export.csv
  challenge-platforms-export.csv
  challenge-technologies-export.csv
</pre>

<hr>
<h4>Or You can use rake task to generate prediction data to the Google Cloud Storage</h4>
<p>
  It assumes that csv files are in Google Cloud Storage, so you need to upload csv files to the Google Storage first.
</p>
<p> And then, </p>
<pre>foreman run rake feed_data</pre>